  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check GitHub OIDC claims
        shell: bash
        run: |
          TOKEN=$(curl -sSf \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
            | jq -r '.value')

          python3 - "$TOKEN" <<'PY'
          import sys
          import json
          import base64

          token = sys.argv[1]
          payload = token.split(".")[1]
          payload += "=" * (-len(payload) % 4)

          claims = json.loads(
              base64.urlsafe_b64decode(payload)
          )

          for key in [
              "iss",
              "aud",
              "sub",
              "repository",
              "repository_owner",
              "ref"
          ]:
              print(f"{key}: {claims.get(key)}")
          PY

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::699061129313:role/GitHubActionsDevOpsCICDRole
          role-session-name: GitHubActionsSession
          aws-region: ap-south-1
