deploy:
  name: Deploy to S3
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::699061129313:role/GitHubActionsDevOpsCICDRole
        role-session-name: GitHubActionsSession
        aws-region: ap-south-1

    - name: Deploy website to S3
      run: |
        aws s3 sync . s3://${{ secrets.S3_BUCKET }} \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "README.md"

    - name: Deployment successful
      run: echo "Website deployed successfully!"
